version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "2333:3000"
    environment:
      - NODE_ENV=production
      - LEMON_HOST=0.0.0.0
      - LEMON_REIDS_HOST=redis
      - LEMON_MONGO_HOST=mongo-node1
    links:
      - redis
    external_links:
      - mongo-node1
      - mongo-node2
      - mongo-node3
networks:
  default:
    external:
      name: my-mongo-cluster